# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

# OpenAPI Configuration
application.title=Chaos Monkey Application
application.description=APIs for Chaos Monkey Application
application.version=1.0.0
application.blog.url=https://eletutour.fr
application.license.name=Apache 2.0
application.license.url=https://www.apache.org/licenses/LICENSE-2.0
application.terms.url=https://eletutour.fr/terms
application.server.url=http://localhost:8080
application.server.description=Local Server

# Resilience4j Configurations
resilience4j.circuitbreaker.instances.recommendationService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.recommendationService.slidingWindowSize=20
resilience4j.circuitbreaker.instances.recommendationService.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.recommendationService.failureRateThreshold=40
resilience4j.circuitbreaker.instances.recommendationService.slowCallRateThreshold=50
resilience4j.circuitbreaker.instances.recommendationService.slowCallDurationThreshold=2s
resilience4j.circuitbreaker.instances.recommendationService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.recommendationService.permittedNumberOfCallsInHalfOpenState=3

resilience4j.retry.instances.recommendationService.maxAttempts=1
resilience4j.retry.instances.recommendationService.waitDuration=200ms

resilience4j.circuitbreaker.instances.streamingService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.streamingService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.streamingService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.streamingService.failureRateThreshold=40
resilience4j.circuitbreaker.instances.streamingService.slowCallRateThreshold=50
resilience4j.circuitbreaker.instances.streamingService.slowCallDurationThreshold=1s
resilience4j.circuitbreaker.instances.streamingService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.streamingService.permittedNumberOfCallsInHalfOpenState=2

resilience4j.retry.instances.streamingService.maxAttempts=1
resilience4j.retry.instances.streamingService.waitDuration=200ms

resilience4j.timelimiter.instances.streamingService.timeoutDuration=1s
resilience4j.timelimiter.instances.streamingService.cancelRunningFuture=true