# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.profiles.active=chaos-monkey
springdoc.show-actuator=true
chaos.monkey.apidoc.enabled=true

management.endpoint.chaosmonkey.enabled=true
# include specific endpoints
management.endpoints.web.exposure.include=health,info,chaosmonkey,env,beans