springdoc:
  show-actuator: true
  packages-to-scan:
    - fr.eletutour
    - org.springframework.boot
    - de.codecentric.spring

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: chaosmonkey, health, info, circuitbreakers, retries
  health:
    circuitbreakers:
      enabled: true
