# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

# OpenAPI Configuration
application.title=Chaos Monkey Application
application.description=APIs for Chaos Monkey Application
application.version=1.0.0
application.blog.url=https://eletutour.fr
application.license.name=Apache 2.0
application.license.url=https://www.apache.org/licenses/LICENSE-2.0
application.terms.url=https://eletutour.fr/terms
application.server.url=http://localhost:8080
application.server.description=Local Server